# Generated by Django 3.1.7 on 2021-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('upvoteCount', models.PositiveIntegerField()),
            ],
        ),
    ]
